name: base
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.0.5
  url_strategy: ^0.2.0
  cupertino_icons: ^1.0.2
  pattern_formatter: ^3.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - .env